"""bookmarks task_id ondelete cascade

Revision ID: 1a397841ccb7
Revises: ae2b89b9cd72
Create Date: 2026-09-29 19:43:23.892844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a397841ccb7'
down_revision: Union[str, Sequence[str], None] = 'ae2b89b9cd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tao lai FK voi ondelete=CASCADE, giu ten mac dinh cua Postgres de downgrade
    # drop dung constraint
    op.drop_constraint('bookmarks_task_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(
        'bookmarks_task_id_fkey', 'bookmarks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookmarks_task_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_task_id_fkey', 'bookmarks', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
