"""day 6 comments index attachments

Revision ID: f3e95957d8d7
Revises: 1a397841ccb7
Create Date: 2026-09-30 11:03:58.141920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e95957d8d7'
down_revision: Union[str, Sequence[str], None] = '1a397841ccb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_attachments_task_id_id', 'attachments', ['task_id', 'id'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by'), 'attachments', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    # Tao lai FK comments.task_id voi ondelete=CASCADE (giu nguyen ten mac dinh cua
    # Postgres de downgrade drop dung constraint)
    op.drop_constraint('comments_task_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(
        'comments_task_id_fkey', 'comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE'
    )
    op.create_index('ix_tasks_status_priority', 'tasks', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_priority', table_name='tasks')
    op.drop_constraint('comments_task_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key('comments_task_id_fkey', 'comments', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index(op.f('ix_attachments_uploaded_by'), table_name='attachments')
    op.drop_index('ix_attachments_task_id_id', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
